baseURL = "https://hikewithtyke.com/"
languageCode = "en-us"
title = "Hike with Tyke"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

enableRobotsTXT = true

[params]
  description = "Hike with Tyke business page."
  instagram = "https://instagram.com/hikewithtyke"
